// adams_puzzles.res - created with RESGen v2.0 RC2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (84):
adams_puzzles.wad
halflife.wad
liquids.wad
gfx/env/dashnight256_bk.bmp
gfx/env/dashnight256_bk.tga
gfx/env/dashnight256_dn.bmp
gfx/env/dashnight256_dn.tga
gfx/env/dashnight256_ft.bmp
gfx/env/dashnight256_ft.tga
gfx/env/dashnight256_lf.bmp
gfx/env/dashnight256_lf.tga
gfx/env/dashnight256_rt.bmp
gfx/env/dashnight256_rt.tga
gfx/env/dashnight256_up.bmp
gfx/env/dashnight256_up.tga
maps/adams_puzzles_beta2.cfg
maps/adams_puzzles_beta2.res
maps/adams_puzzles_beta2.txt
maps/adams_puzzles_beta2_motd.txt
models/adamr/hevcharge_wall.mdl
models/adamr/medkit_wall.mdl
models/adamr/piranha.mdl
models/adamr/potplant.mdl
models/adamr/shark.mdl
models/adamr/sharkT.mdl
sound/adamr/cricket.wav
sound/adamr/erriewind.wav
sound/adamr/electricbuzz.wav
sound/adamr/lava.wav
sound/adamr/megascream.wav
sound/adamr/music/chimandolin.wav
sound/adamr/music/healing_spring.wav
sound/adamr/music/sandman.wav
sound/ambience/alien_beacon.wav
sound/ambience/alien_creeper.wav
sound/ambience/alien_zonerator.wav
sound/ambience/burning3.wav
sound/ambience/computalk1.wav
sound/ambience/drips.wav
sound/ambience/dronemachine3.wav
sound/ambience/flameburst1.wav
sound/ambience/industrial1.wav
sound/ambience/labdrone1.wav
sound/ambience/mechwhine.wav
sound/ambience/rocket_steam1.wav
sound/ambience/techamb1.wav
sound/ambience/techamb2.wav
sound/ambience/the_horror1.wav
sound/ambience/the_horror2.wav
sound/ambience/the_horror3.wav
sound/ambience/the_horror4.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/debris/beamstart14.wav
sound/debris/beamstart8.wav
sound/fans/fan1.wav
sound/fans/fan3.wav
sound/fans/fan4.wav
sound/omg/nomble.wav
sound/omg/sky.wav
sound/omg/start.wav
sound/tur/alec.wav
sound/tur/cave.wav
sound/tur/creepylon.wav
sound/tur/janloop.wav
sound/tur/jazzy.wav
sound/tur/labyrinth.wav
sound/tur/lsd.wav
sound/tur/mutecity.wav
sound/tur/nostalgia.wav
sound/tur/oddity.wav
sound/tur/transformation.wav
sound/tur/trippy.wav
sound/tur/twospaces.wav
sprites/d-tele1.spr
sprites/enter1.spr
sprites/exit1.spr
sprites/flare6.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/moths.spr
sprites/nhth1.spr
sprites/xssmke1.spr
xeno.wad
